version: "3.9"

services:
  yoDriveBackend:
    container_name: YoDriveApi
    image: yodrive
    ports:
      - "5083:5083"
    build:
      context: ./yo_drive_backend
      dockerfile: YoDrive.API/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=yodrivedb:5432;DataBase=yodrivedb;Username=postgres;Password=admin
    depends_on:
      - yoDriveDb
  yoDriveDb:
    container_name: yodrivedb
    image: postgres
    ports:
      - "5446:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "yodrivedb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
volumes:
  pg_data: 
