name: CI/CD YoDrive

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: false 
      
    services:
      postgres:
        image: postgres:16 
        env:
          POSTGRES_DB: yodrivedb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Install EF Core Tools
        run: dotnet tool install --global dotnet-ef --version 7.0.0
      - name: Apply Migrations to PostgreSQL
        run: |
              dotnet ef database update --project YoDrive --connection "Host=localhost;Port=5432;Database=yodrivedb;Username=postgres;Password=admin"
        working-directory: ./YoDrive

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Frontend Dependencies and Build
        run: |
          cd yo_drive_client
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.MY_SECRET_TOKEN }}
          publish_dir: yo_drive_client/build
          publish_branch: gh-pages
