name: CI/CD YoDrive

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm --prefix yo_drive_client install
      - name: Build application
        run: npm --prefix yo_drive_client run build
