name: CI/CD YoDrive

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm install --prefix yo_drive_client
      - name: Build application
        run: npm run build --prefix yo_drive_client
